title: Daehan's jekyll title
author: Daehan
email: chid9202@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a description for testing jekyll
  github page by daehan chi

# social links
twitter_username: chid9202
github_username:  chid9202

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
